services:
  track-my-case-ui:
    env_file:
      - .env
    build:
      context: .
      args:
        BUILD_NUMBER: '1.0.0'
        GIT_REF: 'a1b2c3'
        GIT_BRANCH: main
        NODE_ENV: '${NODE_ENV}'
        NODE_PORT: '${NODE_PORT}'
        SERVICE_URL: '${SERVICE_URL}'
        OIDC_CLIENT_ID: '${OIDC_CLIENT_ID}'
        OIDC_PRIVATE_KEY: '${OIDC_PRIVATE_KEY}'
        OIDC_ISSUER: '${OIDC_ISSUER}'
        IV_DID_URI: '${IV_DID_URI}'
        IV_ISSUER: '${IV_ISSUER}'
        OIDC_TOKEN_AUTH_METHOD: '${OIDC_TOKEN_AUTH_METHOD}'
        OIDC_SCOPES: '${OIDC_SCOPES}'
        OIDC_CLAIMS: '${OIDC_CLAIMS}'
        OIDC_AUTHORIZE_REDIRECT_URL: '${OIDC_AUTHORIZE_REDIRECT_URL}'
        OIDC_POST_LOGOUT_REDIRECT_URL: '${OIDC_POST_LOGOUT_REDIRECT_URL}'
        AUTH_VECTOR_OF_TRUST: '${AUTH_VECTOR_OF_TRUST}'
        IDENTITY_VECTOR_OF_TRUST: '${IDENTITY_VECTOR_OF_TRUST}'
        UI_LOCALES: '${UI_LOCALES}'
        IMMEDIATE_REDIRECT: '${IMMEDIATE_REDIRECT}'
        REQUIRE_JAR: '${REQUIRE_JAR}'
        IDENTITY_SUPPORTED: '${IDENTITY_SUPPORTED}'
    ports:
      # Default HOST_PORT to 9999 for data-analytics platform
      - '3000:${NODE_PORT}'
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=false
      - REDIS_HOST=localhost
      # These will need to match new creds in the seed auth service auth
      - SESSION_SECRET=somesecretvalue
      - NO_HTTPS=true
      - TRACK_MY_CASE_API_URL=http://track-my-case-api:9999
      - TRACK_MY_CASE_API_ENABLED=true

  track-my-case-api:
    build:
      context: ../stg-track-my-case-service
    container_name: track-my-case-api
    ports:
      - '9999:9999'
