services:
  app:
    build:
      context: .
      args:
        BUILD_NUMBER: '1.0.0'
        GIT_REF: 'a1b2c3'
        GIT_BRANCH: main
    ports:
      - '3000:3000'
    environment:
      - PRODUCT_ID=UNASSIGNED
      - SESSION_SECRET=somesecretvalue
      - NO_HTTPS=true
      - POC_PASSWORD=supersecure
      - VALID_OTP=123456
      - POP_LOGIN_OTP=123456
      - POP_PASSWORD=supersecure
