services:
  track-my-case-ui:
    build:
      context: .
      args:
        BUILD_NUMBER: '1.0.0'
        GIT_REF: 'a1b2c3'
        GIT_BRANCH: main
    ports:
      # Default HOST_PORT to 9999 for data-analytics platform
      - '3000:9999'
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=false
      - REDIS_HOST=localhost
      # These will need to match new creds in the seed auth service auth
      - SESSION_SECRET=somesecretvalue
      - NO_HTTPS=true
      - TRACK_MY_CASE_API_URL=http://track-my-case-api:9999
      - TRACK_MY_CASE_API_ENABLED=true

  track-my-case-api:
    build:
      context: ../stg-track-my-case-service
    container_name: track-my-case-api
    ports:
      - '9999:9999'
