services:
  app:
    build:
      context: .
      args:
        BUILD_NUMBER: '1.0.0'
        GIT_REF: 'a1b2c3'
        GIT_BRANCH: main
    ports:
      - '9999:9999'
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=false
      - REDIS_HOST=localhost
      # These will need to match new creds in the seed auth service auth
      - SESSION_SECRET=somesecretvalue
      - NO_HTTPS=true
