name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ministryofjustice/github-actions/code-formatter@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
